<script>
    $(document).ready(function(){
    $("#reply_comment").click(function(){
    $(".replay-box-son").hide();
  });
  $("#repy_comment").click(function(){
    $(".replay-box-son").show();
  });
});
</script>
